# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "56bfc96dd83f36521c584c958bf71f43"
name = "leolin-test-app"
handle = "leolin-test-app"
application_url = "https://midnight-booking-auditor-high.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://midnight-booking-auditor-high.trycloudflare.com/auth/callback",
  "https://midnight-booking-auditor-high.trycloudflare.com/auth/shopify/callback",
  "https://midnight-booking-auditor-high.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false

[build]
dev_store_url = "leo-test-hahaha.myshopify.com"
automatically_update_urls_on_dev = true
